name = "Describables"
uuid = "a5fa1b7c-2817-4d7f-b86b-3a908f100d0e"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics (BCBI)", "contributors"]
version = "1.0.0-DEV"

[compat]
Test = "< 0.0.1, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
